language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t mars5887/docker-react -f Dockerfile.dev .

script:
  - docker run mars5887/docker-react npm run test -- --coverage
