sudo: required
services:
  - docker

before-install:
  - docker build -t mars5887/docker-react -f Dockerfile.dev .

script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker run mars5887/docker-react npm run test -- --coverage
