sudo: required
services:
  - docker

before-install:
  - docker build -t mars5887/docker-react -f Dockerfile.dev .

script:
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD mars5887/docker-react
  - docker run mars5887/docker-react npm run test -- --coverage
