sudo: required
services:
  - docker

before-install:
  - docker build -t mars5887/docker-react -f Dockerfile.dev .

script:
  - docker login mars5887
  - docker run mars5887/docker-react npm run test -- --coverage
